title: Tianle Liu's Homepage
page-top-title: Tianle Liu
top-section-bg-text: Be what you wanna be
home-subtitle: Tianle Liu&ensp;|&ensp;Homepage
copyright-text: '&copy; Tianle Liu 2023-2025. All Rights Reserved.'
